dist: xenial

sudo: true

language:
  - c

addons:
  apt:
    packages:
      - build-essential

script:
  - sudo sh -c "apt update && apt install -y linux-headers-`uname -r`"
  - make -j`nproc --all`

notifications:
  email: false

#deploy:
#  - provider: releases
#    api_key: "${GH_TOKEN}"
#    file:
#      - foo.tar.xz
#    skip_cleanup: true
#    on:
#      tags: true
