dist: xenial

sudo: true

language:
  - c

addons:
  apt:
    packages:
      - build-essential
      - linux-headers

script:
  - make -j`nproc --all`

notifications:
  email: false

#deploy:
#  - provider: releases
#    api_key: "${GH_TOKEN}"
#    file:
#      - foo.tar.xz
#    skip_cleanup: true
#    on:
#      tags: true
